apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: nginx.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: kubernetes
            port:
              number: 443
